# ***Task 1:*** 

### 1. Write a function to compute 5/0 and use try/except to catch the exceptions. 

In [1]:
def divide_by_zero(x,y):
    try:
        result = x // y
        print('The result is {}'.format(result))
    except ZeroDivisionError:
        print('Division By Zero is not possible. Kindly change the denominator.')
        
if __name__ == '__main__':
    a = int(input('Enter a number : '))
    b = int(input('Enter a number : '))
    divide_by_zero(a,b)

Enter a number : 5
Enter a number : 0
Division By Zero is not possible. Kindly change the denominator.


### 2. Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
### Hint: Subject,Verb and Object should be declared in the program as shown below.
### subjects=["Americans ","Indians"]
### verbs=["play","watch"]
### objects=["Baseball","Cricket"]
### Output should come as below:
### Americans play Baseball.
### Americans play Cricket.
### Americans watch Baseball.
### Americans watch Cricket.
### Indians play Baseball.
### Indians play Cricket.
### Indians watch Baseball.
### Indians watch Cricket.


In [2]:
# Defining subjects, verbs, objects
subjects = ["Americans", "Indians"]
verbs = ["play", "watch"]
objects = ["Baseball", "Cricket"]
for subject in subjects:
    for verb in verbs:
        for obj in objects:
            print("{}{}{}".format(subject+' ',verb+' ',obj))

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# *** Task 2: ***

### 1. Write a function so that the columns of the output matrix are powers of the input vector. The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
- HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde. 

In [3]:
import numpy as np

# Defining a function to generate an output matrix which are powers of the input vector
def ouput_matrix(ip_vector):
    x = np.array(ip_vector)
#     print(x)
    N = len(x)
#     print(N)
    '''
    We have to iterate over each element of the vector and by applying exponential operation on each of the element with operand starting from 0 to (n-1)th element and populating the result in a 2D array.
    Finally, applying the Transpose function on the resultant 2D array inorder to obtain the desired output with increasing GP as per Vandermonde Matrix Theory.
    '''
    y = np.array([x**(N-i-1) for i in range(N)])
#     print(y)
    return(y.T)

if __name__ == '__main__':
    input_vector = [1,2,3,4]
    print(ouput_matrix(input_vector))

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
